apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  selector:
    app: prometheus-app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090  # You can specify a port within the range 30000-32767
