# Persistent Volume for Prometheus
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: monitoring-stack-storage-class
  hostPath:
    path: /mnt/prometheusDB

 Persistent Volume Claim for Prometheus
