apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: monitoring-stack
spec:
  replicas: 1
  serviceName: "prometheus-service"
  selector:
    matchLabels:
      app: prometheus-app
  template:
    metadata:
      labels:
        app: prometheus-app
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-pvc
          mountPath: /prometheus
        securityContext:
         runAsUser: 0  # Runs the container as root user
  volumeClaimTemplates:
  - metadata:
      name: prometheus-pvc
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "monitoring-stack-storage-class" # Replace with your storage class
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring-stack
spec:
  type: NodePort
  selector:
    app: prometheus-app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30091 # You can specify a port within the range 30000-32767

